---
label: Config
hide_body: true
is_partial: false
fields:
- type: text
  name: title
  label: Title
  description: Site title
  config:
    required: true
- type: field_group
  name: banner
  label: Banner Configuration
  fields:
  - type: field_group_list
    name: image_list
    label: Banner Images
    description: A list of images to be displayed in a slide show in the page banner
    config:
      labelField: path
    fields:
    - type: file
      name: path
      label: Image
      config:
        required: true
- type: select
  name: palette
  label: Color Palette
  description: The color palette used for the page.
  default: blue
  config:
    required: true
    source:
      type: custom
    options:
    - blue
    - cyan
    - green
    - magenta
- type: field_group
  name: palettes
  label: Palettes
  hidden: true
  fields:
  - type: field_group
    name: blue
    label: Blue
    fields:
    - type: include
      name: include_palette
      label: Palette
      template: palette
  - type: field_group
    name: cyan
    label: Cyan
    fields:
    - type: include
      name: include_palette
      label: Palette
      template: palette
  - type: field_group
    name: green
    label: Green
    fields:
    - type: include
      name: include_palette
      label: Palette
      template: palette
  - type: field_group
    name: magenta
    label: Magenta
    fields:
    - type: include
      name: include_palette
      label: Palette
      template: palette
